"""initial schema

Revision ID: bfb4f8af0f64
Revises: 
Create Date: 2026-07-09 09:35:36.446384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfb4f8af0f64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversations', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('file_path', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_feedbacks_conversation_id'), 'feedbacks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_message_id'), 'feedbacks', ['message_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'feedbacks', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feedbacks', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feedbacks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('knowledge_bases', 'owner_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=False,
               existing_server_default=sa.text("'00000000-0000-0000-0000-000000000000'"))
    op.alter_column('knowledge_bases', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_bases', 'is_official',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_bases', 'allow_copy',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('knowledge_bases', 'copy_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_knowledge_bases_owner_id'), 'knowledge_bases', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_bases', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_bases_owner_id'), table_name='knowledge_bases')
    op.alter_column('knowledge_bases', 'copy_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_bases', 'allow_copy',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('knowledge_bases', 'is_official',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_bases', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_bases', 'owner_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=True,
               existing_server_default=sa.text("'00000000-0000-0000-0000-000000000000'"))
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_message_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_conversation_id'), table_name='feedbacks')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_knowledge_base_id'), table_name='documents')
    op.drop_column('documents', 'file_path')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
